name: gasna_user
description: gas transfer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_database: ^6.0.0
  connectivity: ^0.4.8+6
  google_maps_flutter: ^0.5.28
  outline_material_icons: ^0.1.1
  geolocator: ^5.3.1
  http: ^0.12.1
  provider: ^4.1.2
  flutter_polyline_points: ^0.2.1
  font_awesome_flutter: ^8.8.1
  animated_text_kit: ^2.1.0
  flutter_geofire: ^1.0.3
  permission_handler: ^5.0.0+hotfix.10
  country_code_picker: ^2.0.1
  url_launcher: ^6.0.4
  auto_size_text: ^2.1.0
  flutter_svg: ^0.22.0
  animated_splash_screen: ^1.1.0
  lottie: ^0.7.0+1
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
  fonts:
    - family: Kharabeesh
      fonts:
        - asset: fonts/Kharabeesh-Font.ttf
    - family: JF-Flat-regular
      fonts:
        - asset: fonts/JF-Flat-regular.otf

