name: gasna_user
description: gas transfer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+6

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  firebase_database: ^9.0.6
  connectivity: ^3.0.6
  google_maps_flutter: ^2.1.1
  outline_material_icons: ^0.1.1
  geolocator: ^8.1.1
  http: ^0.13.4
  provider: ^6.0.2
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^9.2.0
  animated_text_kit: ^4.2.1
  flutter_geofire: ^2.0.1 
  permission_handler: ^8.3.0
  country_code_picker: ^2.0.1
  url_launcher: ^6.0.4
  auto_size_text: ^2.1.0
  flutter_svg: ^0.22.0
  animated_splash_screen: ^1.1.0
  lottie: ^0.7.0+1
  smooth_star_rating: ^1.1.1
  fluttertoast: ^7.1.6
  share: ^2.0.4
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
  fonts:
    - family: Kharabeesh
      fonts:
        - asset: fonts/Kharabeesh-Font.ttf
    - family: JF-Flat-regular
      fonts:
        - asset: fonts/JF-Flat-regular.otf

